import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F5F6F5",
  },
  mapWrapper: {
    flex: 1,
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    gap: 12,
  },
  loadingText: {
    color: "#58716A",
    fontSize: 14,
  },
  searchContainer: {
    position: "absolute",
    top: 16,
    left: 16,
    right: 16,
    height: 46,
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 5,
  },
  input: {
    marginLeft: 8,
    flex: 1,
    fontSize: 14,
    color: "#1C1C1C",
  },
  permissionBanner: {
    position: "absolute",
    bottom: 24,
    left: 16,
    right: 16,
    backgroundColor: "#FFF8E7",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  permissionText: {
    flex: 1,
    color: "#7A5200",
    fontSize: 13,
    lineHeight: 18,
  },
  markerPin: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#14342B",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#FFFFFF",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  markerPinGuide: {
    backgroundColor: "#D97706",
  },
  legend: {
    position: "absolute",
    bottom: 20,
    right: 14,
    backgroundColor: "rgba(255,255,255,0.93)",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    gap: 6,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  legendDot: {
    width: 11,
    height: 11,
    borderRadius: 6,
  },
  legendText: {
    fontSize: 12,
    color: "#333333",
    fontWeight: "500",
  },
  callout: {
    width: 180,
    padding: 10,
    gap: 4,
  },
  calloutTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#14342B",
  },
  calloutSubtitle: {
    fontSize: 12,
    color: "#6D7673",
    marginTop: 2,
  },
  calloutAction: {
    fontSize: 12,
    fontWeight: "700",
    color: "#10A95A",
    marginTop: 6,
  },
});
