import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F5F6F5",
  },
  mapWrapper: {
    flex: 1,
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    gap: 12,
  },
  loadingText: {
    color: "#58716A",
    fontSize: 14,
  },
  searchContainer: {
    position: "absolute",
    top: 16,
    left: 16,
    right: 16,
    height: 46,
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 5,
  },
  input: {
    marginLeft: 8,
    flex: 1,
    fontSize: 14,
    color: "#1C1C1C",
  },
  permissionBanner: {
    position: "absolute",
    bottom: 24,
    left: 16,
    right: 16,
    backgroundColor: "#FFF8E7",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  permissionText: {
    flex: 1,
    color: "#7A5200",
    fontSize: 13,
    lineHeight: 18,
  },
  markerLabel: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1.5,
    borderColor: "#D7DEDB",
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
    maxWidth: 130,
  },
  markerLabelSelected: {
    backgroundColor: "#14342B",
    borderColor: "#14342B",
  },
  markerLabelGuide: {
    backgroundColor: "#FFFFFF",
    borderColor: "#D97706",
  },
  markerLabelGuideSelected: {
    backgroundColor: "#D97706",
    borderColor: "#D97706",
  },
  markerLabelText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#14342B",
  },
  markerLabelTextSelected: {
    color: "#FFFFFF",
  },

  bottomStrip: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
  },
  bottomStripContent: {
    paddingHorizontal: 16,
    paddingBottom: 20,
    paddingTop: 8,
    gap: 12,
  },
  bottomCard: {
    width: 220,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 5,
  },
  bottomCardImage: {
    width: "100%",
    height: 120,
    backgroundColor: "#E8EDEB",
  },
  bottomCardContent: {
    padding: 10,
    gap: 2,
  },
  bottomCardType: {
    fontSize: 10,
    fontWeight: "700",
    color: "#10A95A",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  bottomCardTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#14342B",
  },
  bottomCardSubtitle: {
    fontSize: 12,
    color: "#6D7673",
  },

  callout: {
    width: 180,
    padding: 10,
    gap: 4,
  },
  calloutTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#14342B",
  },
  calloutSubtitle: {
    fontSize: 12,
    color: "#6D7673",
    marginTop: 2,
  },
  calloutAction: {
    fontSize: 12,
    fontWeight: "700",
    color: "#10A95A",
    marginTop: 6,
  },

  startButton: {
    marginTop: 8,
    backgroundColor: "#14342B",
    borderRadius: 10,
    paddingVertical: 6,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  startButtonActive: {
    backgroundColor: "#D93025",
  },
  startButtonText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "700",
  },
  navBanner: {
    position: "absolute",
    bottom: 8,
    left: 16,
    right: 16,
    backgroundColor: "#14342B",
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 6,
  },
  navBannerText: {
    flex: 1,
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "600",
  },
  stopButton: {
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  stopButtonText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "700",
  },
});
