import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#14342B",
  },
  imageWrapper: {
    position: "relative",
    overflow: "hidden",
  },
  image: {
    width: "100%",
    height: 310,
  },
  backButton: {
    position: "absolute",
    top: 18,
    left: 18,
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "rgba(0,0,0,0.38)",
    justifyContent: "center",
    alignItems: "center",
  },
  ratingBadge: {
    position: "absolute",
    bottom: 44,
    left: 18,
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 7,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 4,
  },
  ratingBadgeValue: {
    fontWeight: "800",
    fontSize: 16,
    color: "#14342B",
  },
  ratingBadgeLabel: {
    fontSize: 13,
    color: "#6D7673",
  },
  content: {
    flexGrow: 1,
    backgroundColor: "#F5F6F5",
    marginTop: -24,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    paddingHorizontal: 18,
    paddingTop: 22,
    paddingBottom: 32,
  },
  typeRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  type: {
    fontSize: 12,
    fontWeight: "700",
    color: "#10A95A",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  title: {
    fontSize: 26,
    fontWeight: "800",
    color: "#14342B",
    marginBottom: 16,
    lineHeight: 32,
  },
  statsRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 18,
  },
  statCard: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 12,
    alignItems: "center",
    gap: 3,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  statValue: {
    fontSize: 20,
    fontWeight: "800",
    color: "#14342B",
  },
  statLabel: {
    fontSize: 11,
    color: "#8A9490",
    textTransform: "uppercase",
    fontWeight: "600",
    letterSpacing: 0.4,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#14342B",
    marginBottom: 10,
    marginTop: 18,
  },
  description: {
    fontSize: 15,
    lineHeight: 23,
    color: "#3D5249",
  },
  chips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 4,
  },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "#E8F0ED",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  chipText: {
    fontSize: 13,
    color: "#14342B",
    fontWeight: "600",
  },
  gallery: {
    marginBottom: 6,
  },
  galleryImage: {
    width: 200,
    height: 140,
    borderRadius: 14,
  },
  linksSection: {
    marginTop: 8,
  },
  linksList: {
    marginTop: 12,
    gap: 10,
  },
  linkCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  linkCopy: {
    flex: 1,
    marginRight: 12,
  },
  linkLabel: {
    fontSize: 15,
    fontWeight: "700",
    color: "#14342B",
    marginBottom: 3,
  },
  linkUrl: {
    fontSize: 13,
    color: "#8A9490",
  },
  primaryButton: {
    marginTop: 22,
    backgroundColor: "#14342B",
    height: 52,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#14342B",
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 3,
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "700",
  },
  ratingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 12,
  },
  ratingLabel: {
    fontSize: 14,
    color: "#6D7673",
    marginLeft: 6,
  },
  reviewCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 8,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  reviewForm: {
    marginTop: 14,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#E8EEEB",
  },
  reviewSubmitBtn: {
    backgroundColor: "#14342B",
    height: 46,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
  },

  // ─── Despegar-style rating badge ─────────────────────────────────────────
  ratingHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginBottom: 14,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 14,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  scoreBadge: {
    backgroundColor: "#14342B",
    borderRadius: 10,
    width: 54,
    height: 54,
    justifyContent: "center",
    alignItems: "center",
  },
  scoreValue: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "800",
  },
  scoreLabel: {
    fontSize: 16,
    fontWeight: "800",
    color: "#14342B",
  },
  reviewCount: {
    fontSize: 13,
    color: "#8A9490",
    marginTop: 3,
  },

  // ─── Amenity grid (Despegar-style chips) ─────────────────────────────────
  amenityGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 4,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingTop: 6,
    paddingBottom: 10,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  amenityItem: {
    width: "50%",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    paddingVertical: 10,
    paddingRight: 10,
  },
  amenityName: {
    fontSize: 13,
    fontWeight: "700",
    color: "#14342B",
  },
  amenityDesc: {
    fontSize: 12,
    color: "#6D7673",
    marginTop: 2,
  },
});
