import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F5F6F5",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 12,
  },
  backButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#E8EDEB",
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitle: {
    flex: 1,
    fontSize: 17,
    fontWeight: "800",
    color: "#14342B",
  },
  container: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 16,
    paddingBottom: 32,
    gap: 14,
  },
  heroImage: {
    width: "100%",
    height: 220,
    borderRadius: 20,
  },
  heroImagePlaceholder: {
    backgroundColor: "#14342B",
    justifyContent: "center",
    alignItems: "center",
  },
  heroImageCategory: {
    color: "#76E2B3",
    fontSize: 16,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  categoryPill: {
    alignSelf: "flex-start",
    backgroundColor: "#EAF7F1",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  categoryText: {
    color: "#1B7754",
    fontSize: 12,
    fontWeight: "700",
  },
  typeBadge: {
    alignSelf: "flex-start",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  typeBadgeSuggestion: {
    backgroundColor: "#E6F0FF",
  },
  typeBadgeQuestion: {
    backgroundColor: "#FFF1DE",
  },
  typeBadgeText: {
    fontSize: 12,
    fontWeight: "700",
  },
  typeBadgeTextSuggestion: {
    color: "#1B4FA6",
  },
  typeBadgeTextQuestion: {
    color: "#A65C1B",
  },
  postTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "#14342B",
    lineHeight: 30,
  },
  authorRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  authorBadge: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#E6F5EE",
    alignItems: "center",
    justifyContent: "center",
  },
  authorBadgeText: {
    color: "#14342B",
    fontWeight: "800",
    fontSize: 14,
  },
  authorName: {
    color: "#173B32",
    fontWeight: "700",
    fontSize: 14,
  },
  authorRole: {
    color: "#72847D",
    fontSize: 12,
    marginTop: 2,
  },
  summary: {
    color: "#14342B",
    fontSize: 16,
    fontWeight: "600",
    lineHeight: 24,
  },
  body: {
    color: "#3D5249",
    fontSize: 15,
    lineHeight: 24,
  },
  divider: {
    height: 1,
    backgroundColor: "#E8EDEB",
    marginVertical: 4,
  },
  actionsRow: {
    flexDirection: "row",
    gap: 12,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: "#EEF3F1",
  },
  actionButtonPositive: {
    backgroundColor: "#18B678",
  },
  actionText: {
    color: "#173B32",
    fontWeight: "700",
    fontSize: 15,
  },
  actionTextActive: {
    color: "#FFFFFF",
  },
  commentsTitle: {
    color: "#173B32",
    fontWeight: "800",
    fontSize: 16,
  },
  noComments: {
    color: "#8A9490",
    fontSize: 14,
    fontStyle: "italic",
  },
  commentCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    padding: 12,
  },
  commentBadge: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#E6F5EE",
    alignItems: "center",
    justifyContent: "center",
  },
  commentAuthor: {
    color: "#14342B",
    fontWeight: "700",
    fontSize: 12,
    marginBottom: 2,
  },
  commentText: {
    color: "#3D5249",
    lineHeight: 20,
    fontSize: 14,
  },
  commentComposer: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 10,
    marginTop: 4,
  },
  commentInput: {
    flex: 1,
    minHeight: 46,
    maxHeight: 120,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#D5DEDA",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
    color: "#173B32",
    fontSize: 14,
  },
  sendButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#14342B",
    alignItems: "center",
    justifyContent: "center",
  },
  commentCounter: {
    color: "#8A9490",
    fontSize: 12,
    alignSelf: "flex-end",
    marginTop: -6,
  },
  commentCounterLimit: {
    color: "#D93025",
  },
  notFound: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  notFoundText: {
    color: "#8A9490",
    fontSize: 16,
  },
});
